name: myFirstWorkflow
#to get trigger on every push in this repo
on: push

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps:
      - name: Running Single Command in Job1
        run: echo "Hi this is my first github workflow"
      - name: Checking os release for github hosted runner
        run: cat /etc/os-release
      - name: Calling Sleep
        run: sleep 20
  job2:
    name: JOB2
    runs-on: ubuntu-latest
    steps:
      - name: Checking the Hostname for runner
        run: hostname
      - name: Running multiple commands
        run: |
          echo "Hi from Mikeey"
          echo "current time is `date`"
          sleep 20
